version: '2.1'
services:

  php:
    extends:
      file: _docker/php.yml
      service: php

  mysql:
    extends:
      file: _docker/mysql.yml
      service: mysql

  mongo:
    extends:
      file: _docker/mongo.yml
      service: mongo

  redis:
    extends:
      file: _docker/redis.yml
      service: redis

networks:
  net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.13.0.0/16
         gateway: 10.13.0.1

volumes:
  data-volume:
