apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: db  
  labels:
    component: db
    team: devops
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
    component: db
  
