apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis
  namespace: db  
  labels:
    component: db
    team: devops
    app: redis
spec:
  replicas: 1
  updateStrategy:
    type: OnDelete
  serviceName: redis
  template:
    metadata:
      labels:
        component: db
        app: redis
        team: devops
    spec:
      containers:
      - name: redis-db
        image:  redis:5.0.3-alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "100m"
        volumeMounts:
          - mountPath: /data
            name: data
          - name: redis-config-volume
            mountPath: /etc/redis/
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-1
      volumes:
        - name: redis-config-volume
          configMap:
            name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: ssd
      resources:
        requests:
          storage: 5Gi
