apiVersion: v1
kind: Service
metadata:
  name: laravel
  namespace: laravel
spec:
  selector:
    app: laravel
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
