version: '2.1'
services:
  mongo:
    container_name: mongo
    image: mvertes/alpine-mongo:4.0.1-0
    mem_limit: 1g
    memswap_limit: 1g
    cpu_shares: 20
    ports:
      - 37017:27017
      - 38017:28017
    networks:
      net:
        ipv4_address: 10.13.0.21
    volumes:
      - data-volume:/data/mongodb:rw
