version: '2.1'
services:
  nginx:
    container_name: nginx
    image: nginx:1.14.2-alpine
    mem_limit: 500000000 #500m
    memswap_limit: 500000000 # 500m
    cpu_shares: 20
    ports:
      - "8080:80"
      - "8043:443"
    networks:
      net:
        ipv4_address: 10.13.0.100
    extra_hosts:
      # services
      - "php:      10.13.0.6"
      - "mysql:    10.13.0.20"
      - "mongo:    10.13.0.21"
      - "mongodb:  10.13.0.21"
      - "redis:    10.13.0.22"
    volumes:
      - ./nginx:/image/
      - ./nginx/files/config/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/files/config/site.d:/etc/nginx/site.d
      - ./nginx/files/config/ssl:/etc/nginx/ssl
      - ./nginx/files/config/nginx.conf:/etc/nginx/nginx.conf
      - data-volume:/var/log/nginx
      - ./../:/var/www/
