version: '2.1'
services:
  php:
    container_name: php
    image: clouddrove/php:7.2.12-0
    mem_limit: 2000000000 #2g
    memswap_limit: 2000000000 #2g
    cpu_shares: 30
    privileged: true
    ports:
      - "8443:443"  # nginx ssl
      - "2222:22"   # ssh
      - "9003:9003" # xdebug
      - "9001:9001" # supervisor admin
      - "9110:9110" # php
    entrypoint: /image/start.sh

    volumes:
      - ./php:/image/
      - ./../:/var/www/
      - data-volume:/var/log/php
      - ./php/etc/sshd.conf:/etc/ssh/sshd_config
      - ~/.ssh:/root/.ssh
      - ./php/etc/zshrc:/root/.zshrc
      - ./php/etc/zsh/aliases.conf:/root/.aliases
      - ./php/etc/zsh/extra.conf:/root/.extra
      - ~/.ssh:/home/www-data/.ssh
      - ./php/etc/zshrc:/home/www-data/.zshrc
      - ./php/etc/zsh/aliases.conf:/home/www-data/.aliases
      - ./php/etc/zsh/extra.conf:/home/www-data/.extra
      - ./php/php.ini:/usr/local/etc/php/php.ini

    networks:
      net:
        ipv4_address: 10.13.0.6

    extra_hosts:
      # services
      - "php: 10.13.0.6"
      - "mysql: 10.13.0.20"
      - "mongo: 10.13.0.21"
      - "mongodb: 10.13.0.21"
      - "redis: 10.13.0.22"


      # local domain
      - "lumana-api.local: 10.10.0.100"

