version: '2.1'
services:
  php:
    container_name: php
    image: clouddrove/php:7.3.3-fpm-nginx
    mem_limit: 2000000000 #2g
    memswap_limit: 2000000000 #2g
    cpu_shares: 30
    privileged: true
    ports:
      - "2222:22"   # ssh
      - "8080:80"
      - "8443:443"
    entrypoint: /image/start.sh
    volumes:
      - ./php:/image/
      - ./../:/var/www/
      - ~/.ssh:/root/.ssh
      - ~/.ssh:/home/www-data/.ssh
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - data-volume:/var/log/nginx
      - data-volume:/var/log/php
    networks:
      net:
        ipv4_address: 10.13.0.6

    extra_hosts:
      # services
      - "mysql: 10.13.0.20"
      - "mongo: 10.13.0.21"
      - "mongodb: 10.13.0.21"
      - "redis: 10.13.0.22"


      # local domain
      - "lumana-api.local: 10.10.0.6"

