version: '2.1'
services:
  redis:
    container_name: redis
    image: redis:5.0.3-alpine
    mem_limit: 500m
    memswap_limit: 500m
    cpu_shares: 10
    ports:
      - 7379:6379
      - 36379:26379
    networks:
      net:
        ipv4_address: 10.13.0.22
    volumes:
      - data-volume:/var/lib/redis
